services:
  - type: web
    name: catalog-django
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn catalog_back.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
